name: Docker Image CI

env:
  CONTAINER_NAME: bitbucket-dashboard:$(date +%s)
  IMAGE_NAME: bitbucket-dashboard:$(date +%s)
  DOCKER_PORT: 80
  EXTERNAL_PORT: 80

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME
    - name: Run the Docker image
      run: docker run --name $CONTAINER_NAME -p $DOCKER_PORT:$EXTERNAL_PORT $IMAGE_NAME
