name: Docker Image CI

env:
  CONTAINER_NAME: bitbucket-dashboard:$(date +%s)
  IMAGE_NAME: bitbucket-dashboard:$(date +%s)
  DOCKER_PORT: 80
  EXTERNAL_PORT: 80

concurrency:
  group: "pages"
  cancel-in-progress: false

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs: 
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.5.0
        with:
          tags: bitbucket-dashboard:latest
          push: false
      - uses: oxidfabian/docker-run-action@v1
        with:
          image: bitbucket-dashboard:latest
