name: Docker Image CI

env:
  CONTAINER_NAME: bitbucket-dashboard:$(date +%s)
  IMAGE_NAME: bitbucket-dashboard:$(date +%s)
  DOCKER_PORT: 80
  EXTERNAL_PORT: 80

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

runs:
  using: 'docker'
  image: 'Dockerfile'
